---
rules:
    - ['*.html', [!ruby/regexp '/^cr|none$/', !ruby/regexp '/^true$/']]
    - ['*[.-]min.*', [!ruby/regexp '/^none$/', !ruby/regexp '/^false$/']]
    - ['*.{reg,cmd,bat,ps1,cs,fs,vbs,xaml,csproj,sln,aip}', [!ruby/regexp '/^crlf|none$/', !ruby/regexp '/^true|false$/']]
    - ['*', [!ruby/regexp '/^lf|none$/', !ruby/regexp '/^true$/']]
